### ISSUE TITLE
Feature: Add baseline support

### ISSUE THREAD

**Issue by squalx** [Draveness/Typeset#10]
I have a fix for this, only I can't push code. @Draveness , do you think you can give me access? Then I'll make the PR.

Thanks.

**Comment by draveness** [comment]
You can open a pull request to submit ur code
From Draveness
On 周三, 9月 30, 2015 at 02:58, Draveness/Typeset
reply@reply.github.com
wrote:
I have a fix for this, only I can't push code. @Draveness [https://github.com/Draveness] , do you think you can give me access? Then I'll make the PR.

Thanks.
