### ISSUE TITLE
iOS 7下连体字的问题

### ISSUE THREAD

**Issue by luosky** [Draveness/Typeset#4]
在 iOS 7下，像“Shuffle” 这样的字，如果用 `@"Shuffle".typeset.match(@"f").red.string` ，会得到 ffl 都变红的结果。
解决方案是将这个 AttributedString 的NSLigatureAttributeName属性设为0：
`[mas addAttribute:NSLigatureAttributeName value:@(0) range:NSMakeRange(0, mas.length)];`

但我不确定是否要把这个设置整合进来，还是说把默认值改为0?  你觉得呢？

参见：
- [NSAttributedString double “ff” counted as single “f” when using system font in iOS 7](http://stackoverflow.com/questions/22532097/nsattributedstring-double-ff-counted-as-single-f-when-using-system-font-in-i)
- [“The fi bug” A weird iOS 7 attributed text bug](http://stackoverflow.com/questions/21369439/the-fi-bug-a-weird-ios-7-attributed-text-bug)

**Comment by draveness** [comment]
我觉得可以把这个整合进来, 如果方便的话, 你可以提交一个 pull request, 不过在 iOS 8 上确实没有这个问题. :+1:
